name: "Nix Build"

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Build x86_64-pc-windows-gnu target with Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Build windows package
        run: nix build .#x86_64-pc-windows-gnu
      - name: Make release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "result/bin/octarou.exe":

